"""empty message

Revision ID: f74a36b5c852
Revises: 
Create Date: 2024-11-12 00:03:33.959105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f74a36b5c852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('User',
    sa.Column('id_user', sa.String(length=50), nullable=False),
    sa.Column('nameUser', sa.String(length=255), nullable=False),
    sa.Column('lastName', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Role.role_id'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nameUser')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('role_name')

    op.drop_table('role')
    op.drop_table('autocorrection')
    op.drop_table('manualreview')
    op.drop_table('department')
    op.drop_table('enrollment_professor')
    op.drop_table('university')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('lastName')
        batch_op.drop_index('nameUser')

    op.drop_table('user')
    op.drop_table('enrollment_student')
    op.drop_table('submission')
    op.drop_table('studentgroup')
    op.drop_table('course')
    op.drop_table('registrationrequest')
    op.drop_table('faculty')
    op.drop_table('assignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('assignmentId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('NRC', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('id_professor', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('groupId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['NRC'], ['course.NRC'], name='assignment_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['groupId'], ['studentgroup.groupId'], name='assignment_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_professor'], ['user.id_user'], name='assignment_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignmentId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('faculty',
    sa.Column('facultyId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('facultyName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('facultyType', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('universityId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['universityId'], ['university.universityId'], name='faculty_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('facultyId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('registrationrequest',
    sa.Column('requestId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('request_type', mysql.ENUM('Profesor', 'Estudiante'), nullable=False),
    sa.Column('status', mysql.ENUM('Pendiente', 'Aceptada', 'Denegada'), server_default=sa.text("'Pendiente'"), nullable=True),
    sa.Column('requested_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], name='registrationrequest_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requestId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('course',
    sa.Column('NRC', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('codeCourse', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nameCourse', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('idDepartment', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idDepartment'], ['department.idDepartment'], name='course_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('NRC'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('studentgroup',
    sa.Column('groupId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('NRC', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('groupName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_professor', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['NRC'], ['course.NRC'], name='studentgroup_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_professor'], ['user.id_user'], name='studentgroup_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('groupId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('submission',
    sa.Column('submissionId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignmentId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_student', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('submission_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('grade', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('taskReviewed', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('taskSubmitted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignmentId'], ['assignment.assignmentId'], name='submission_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_student'], ['user.id_user'], name='submission_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submissionId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('enrollment_student',
    sa.Column('enroll_studentId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_student', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NRC', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['NRC'], ['course.NRC'], name='enrollment_student_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_student'], ['user.id_user'], name='enrollment_student_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enroll_studentId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id_user', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nameUser', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='user_ibfk_1'),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('nameUser', ['nameUser'], unique=True)
        batch_op.create_index('lastName', ['lastName'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('university',
    sa.Column('universityId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('universityName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uniCountry', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uniSede', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uniAdress', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('universityId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('enrollment_professor',
    sa.Column('enroll_profeId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_professor', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('NRC', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['NRC'], ['course.NRC'], name='enrollment_professor_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_professor'], ['user.id_user'], name='enrollment_professor_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enroll_profeId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('department',
    sa.Column('idDepartment', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nameDepartment', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('facultyId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facultyId'], ['faculty.facultyId'], name='department_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idDepartment'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('manualreview',
    sa.Column('reviewId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submissionId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_professor', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grade', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('reviewDate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_professor'], ['user.id_user'], name='manualreview_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submissionId'], ['submission.submissionId'], name='manualreview_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reviewId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('autocorrection',
    sa.Column('autoCorrectionId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submissionId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['submissionId'], ['submission.submissionId'], name='autocorrection_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('autoCorrectionId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('role_name', ['role_name'], unique=True)

    op.drop_table('User')
    op.drop_table('Role')
    # ### end Alembic commands ###
